### ISSUE TITLE
Running STABLE algorithm results in increasing cost

### ISSUE THREAD

**Issue by leo4048111** [JunjieYang97/MRVRBO#2]
i ran the STABLE implementation for comparison with MRBO in mnist_exp.py and after each epoch the cost goes up tremendously, is this normal?

**Comment by JunjieYang97** [comment]
It is normal. STABLE requires computing Hessian explicitly which causes large variance in terms of hyper gradient estimation. Usually, we will prefer to use much smaller learning rate for stable training.
